/**
 * Mock-данные для демо "Идёт поиск лидов…" (без реального API).
 */

import type { LeadRow } from './types';

export const MOCK_DEMO_RESULTS: LeadRow[] = [
  {
    id: '1',
    domain: 'example-cafe.example',
    phone: '+7 999 123-45-67',
    email: 'info@example-cafe.example',
    score: 85,
    issues: { robots: true, sitemap: true, titleDuplicates: false, descriptionDuplicates: false },
    seo: {
      robots: 'OK',
      sitemap: 'OK',
      metaTitle: 'Кафе — Пример',
      metaDesc: 'Описание.',
      h1: 'Кафе',
      http: '200',
      pagesCrawled: 5,
    },
    status: 'ok',
    outreachText: '',
  },
  {
    id: '2',
    domain: 'studio.example',
    phone: '+7 999 234-56-78',
    email: null,
    score: 72,
    issues: { robots: true, sitemap: false, titleDuplicates: false, descriptionDuplicates: true },
    seo: {
      robots: 'OK',
      sitemap: 'не найдена',
      metaTitle: 'Студия',
      metaDesc: '—',
      h1: 'Студия',
      http: '200',
      pagesCrawled: 3,
    },
    status: 'ok',
    outreachText: '',
  },
  {
    id: '3',
    domain: 'shop.example',
    phone: null,
    email: 'contact@shop.example',
    score: 68,
    issues: { robots: false, sitemap: false, titleDuplicates: true, descriptionDuplicates: false },
    seo: {
      robots: 'не найден',
      sitemap: 'не найдена',
      metaTitle: 'Магазин',
      metaDesc: 'Магазин.',
      h1: 'Главная',
      http: '200',
      pagesCrawled: 1,
    },
    status: 'ok',
    outreachText: '',
  },
  {
    id: '4',
    domain: 'agency.example',
    phone: '+7 999 456-78-90',
    email: 'hello@agency.example',
    score: 91,
    issues: { robots: true, sitemap: true, titleDuplicates: false, descriptionDuplicates: false },
    seo: {
      robots: 'OK',
      sitemap: 'OK',
      metaTitle: 'Агентство — Услуги',
      metaDesc: 'Описание агентства.',
      h1: 'Агентство',
      http: '200',
      pagesCrawled: 8,
    },
    status: 'ok',
    outreachText: '',
  },
  {
    id: '5',
    domain: 'service.example',
    phone: '+7 999 567-89-01',
    email: null,
    score: 55,
    issues: { robots: false, sitemap: false, titleDuplicates: true, descriptionDuplicates: true },
    seo: {
      robots: 'Disallow:/',
      sitemap: 'не найдена',
      metaTitle: '-',
      metaDesc: '-',
      h1: '-',
      http: '200',
      pagesCrawled: 0,
    },
    status: 'error',
    outreachText: '',
  },
  {
    id: '6',
    domain: 'blog.example',
    phone: null,
    email: 'team@blog.example',
    score: 78,
    issues: { robots: true, sitemap: true, titleDuplicates: false, descriptionDuplicates: false },
    seo: {
      robots: 'OK',
      sitemap: 'OK',
      metaTitle: 'Блог',
      metaDesc: 'Статьи.',
      h1: 'Блог',
      http: '200',
      pagesCrawled: 12,
    },
    status: 'ok',
    outreachText: '',
  },
];
